import Head from 'next/head'
import utils from '../styles/utils.module.css';

import Nav from '../components/hoc/Nav';
import Hero from '../components/hoc/Hero';

import Section from '../components/loc/Section';
import Panel from '../components/loc/Panel';
import Button from '../components/loc/Button';
import Contact from '../components/loc/Contact';

import fr from '../i18n/fr.json';
import en from '../i18n/en.json';

export async function getStaticProps({ locale }) {
    let lang = en;
    if (locale === 'fr') {
        lang = fr;
    }
    return {
        props: {
            lang,
        },
    }
}

const WORK_STYLE = [
    {
        panel: 'yellow',
        buttons: ['yellow', 'black'],
        image: '/img/caliko-preview.png',
    },
    {
        panel: 'black',
        buttons: ['black', 'white'],
        image: '/img/fst-preview.png',
    },
    {
        panel: 'green',
        buttons: ['green', 'black'],
        image: '/img/something-preview.png',
    }
];
const SKILL_ICONS = [
    ['python', 'rust'],
    ['node', 'rust', 'react', 'fastify'],
    ['swift', 'react', 'rust', 'tauri'],
];

const Home = ({ lang }) => {
    return (
        <div>
            <Head>
                <title>{lang.head.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Nav lang={lang} />
            <Hero lang={lang} />

            <div id="work" />
            <Section style="blue">
                <div className={utils.phoneSpacer} />
                <h1>{lang.work.title}</h1>
                <h2>{lang.work.subtitle}</h2>
                <div className={utils.phoneSpacer} />
                {lang.work.works.map((work, index) => {
                    return (
                        <Panel.Split
                            key={index}
                            style={WORK_STYLE[index].panel}
                            image={WORK_STYLE[index].image}
                            isLayoutInverted={index % 2 === 0}>
                            <h3>{work.title}</h3>
                            <h2>{work.subtitle}</h2>
                            <p>{work.description}</p>
                            <Button.Group>
                                <Button.Button color={WORK_STYLE[index].buttons[0]} style="inverted">
                                    {lang.work.learn_more}
                                </Button.Button>
                                <Button.Button color={WORK_STYLE[index].buttons[1]} style="outline">
                                    {lang.work.learn_more}
                                </Button.Button>
                            </Button.Group>
                        </Panel.Split>
                    )
                })}
                <div className={utils.phoneSpacer} />
                <Button.Button color="yellow" style="" href="https://github.com/xavierhamel">
                    {lang.work.more}
                </Button.Button>
                <div className={utils.phoneSpacer} />
            </Section>

            <div id="skill" />
            <Section style="cross">
                <Panel.Panel title={lang.skill.title}>
                    {lang.skill.skills.map((skill, index) => {
                        return (
                            <div key={index}>
                                <Panel.HeaderWithIcons
                                    title={skill.title}
                                    icons={SKILL_ICONS[index]}
                                />
                                <p>{skill.description}</p>
                            </div>
                        )
                    })}
                </Panel.Panel>
            </Section>

            <div id="contact" />
            <Section style="yellow">
                <div className={utils.phoneSpacer} />
                <h2>{lang.contact.subtitle}</h2>
                <h1>{lang.contact.title}</h1>
                <Contact.Contacts>
                    <Contact.Contact type="email">hire@xavierhamel.io</Contact.Contact>
                    <Contact.Contact type="linkedin">Xavier Hamel</Contact.Contact>
                    <Contact.Contact type="github">@xavierhamel</Contact.Contact>
                </Contact.Contacts>
                <p>{lang.contact.available}</p>
                <div className={utils.phoneSpacer} />
            </Section>

            <Section style="black">
                <div className={utils.phoneSpacer} />
                <p>{lang.footer.title}</p>
                <div className={utils.phoneSpacer} />
            </Section>
        </div>
    )
};

export default Home;
